################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (11.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
App/BSP/stm32f407vet6_blackpill_v2.3.1 \
App/Core/Src \
App/Drivers/hal \
App/Drivers/ports \
App/Middlewares/fatfs/source \
App/Modules/Display \
App/Modules/GUI/lvgl/src/core \
App/Modules/GUI/lvgl/src/display \
App/Modules/GUI/lvgl/src/draw/convert/helium \
App/Modules/GUI/lvgl/src/draw/convert \
App/Modules/GUI/lvgl/src/draw/convert/neon \
App/Modules/GUI/lvgl/src/draw/dma2d \
App/Modules/GUI/lvgl/src/draw/espressif/ppa \
App/Modules/GUI/lvgl/src/draw/eve \
App/Modules/GUI/lvgl/src/draw \
App/Modules/GUI/lvgl/src/draw/nanovg \
App/Modules/GUI/lvgl/src/draw/nema_gfx \
App/Modules/GUI/lvgl/src/draw/nxp/g2d \
App/Modules/GUI/lvgl/src/draw/nxp/pxp \
App/Modules/GUI/lvgl/src/draw/opengles \
App/Modules/GUI/lvgl/src/draw/renesas/dave2d \
App/Modules/GUI/lvgl/src/draw/sdl \
App/Modules/GUI/lvgl/src/draw/snapshot \
App/Modules/GUI/lvgl/src/draw/sw/blend/helium \
App/Modules/GUI/lvgl/src/draw/sw/blend \
App/Modules/GUI/lvgl/src/draw/sw/blend/neon \
App/Modules/GUI/lvgl/src/draw/sw/blend/riscv_v \
App/Modules/GUI/lvgl/src/draw/sw \
App/Modules/GUI/lvgl/src/draw/vg_lite \
App/Modules/GUI/lvgl/src/drivers/display/drm \
App/Modules/GUI/lvgl/src/drivers/display/fb \
App/Modules/GUI/lvgl/src/drivers/display/ft81x \
App/Modules/GUI/lvgl/src/drivers/display/ili9341 \
App/Modules/GUI/lvgl/src/drivers/display/lcd \
App/Modules/GUI/lvgl/src/drivers/display/nv3007 \
App/Modules/GUI/lvgl/src/drivers/display/nxp_elcdif \
App/Modules/GUI/lvgl/src/drivers/display/renesas_glcdc \
App/Modules/GUI/lvgl/src/drivers/display/st7735 \
App/Modules/GUI/lvgl/src/drivers/display/st7789 \
App/Modules/GUI/lvgl/src/drivers/display/st7796 \
App/Modules/GUI/lvgl/src/drivers/display/st_ltdc \
App/Modules/GUI/lvgl/src/drivers/draw/eve \
App/Modules/GUI/lvgl/src/drivers/evdev \
App/Modules/GUI/lvgl/src/drivers/libinput \
App/Modules/GUI/lvgl/src/drivers/nuttx \
App/Modules/GUI/lvgl/src/drivers/opengles/assets \
App/Modules/GUI/lvgl/src/drivers/opengles/glad/src \
App/Modules/GUI/lvgl/src/drivers/opengles \
App/Modules/GUI/lvgl/src/drivers/opengles/opengl_shader \
App/Modules/GUI/lvgl/src/drivers/qnx \
App/Modules/GUI/lvgl/src/drivers/sdl \
App/Modules/GUI/lvgl/src/drivers/uefi \
App/Modules/GUI/lvgl/src/drivers/wayland \
App/Modules/GUI/lvgl/src/drivers/windows \
App/Modules/GUI/lvgl/src/drivers/x11 \
App/Modules/GUI/lvgl/src/font/binfont_loader \
App/Modules/GUI/lvgl/src/font/fmt_txt \
App/Modules/GUI/lvgl/src/font/font_manager \
App/Modules/GUI/lvgl/src/font/imgfont \
App/Modules/GUI/lvgl/src/font \
App/Modules/GUI/lvgl/src/indev \
App/Modules/GUI/lvgl/src/layouts/flex \
App/Modules/GUI/lvgl/src/layouts/grid \
App/Modules/GUI/lvgl/src/layouts \
App/Modules/GUI/lvgl/src/libs/FT800-FT813 \
App/Modules/GUI/lvgl/src/libs/barcode \
App/Modules/GUI/lvgl/src/libs/bin_decoder \
App/Modules/GUI/lvgl/src/libs/bmp \
App/Modules/GUI/lvgl/src/libs/ffmpeg \
App/Modules/GUI/lvgl/src/libs/freetype \
App/Modules/GUI/lvgl/src/libs/frogfs/src \
App/Modules/GUI/lvgl/src/libs/fsdrv \
App/Modules/GUI/lvgl/src/libs/gif \
App/Modules/GUI/lvgl/src/libs/gltf/gltf_data \
App/Modules/GUI/lvgl/src/libs/gltf/gltf_environment \
App/Modules/GUI/lvgl/src/libs/gltf/gltf_view/assets \
App/Modules/GUI/lvgl/src/libs/gltf/math \
App/Modules/GUI/lvgl/src/libs/gstreamer \
App/Modules/GUI/lvgl/src/libs/libjpeg_turbo \
App/Modules/GUI/lvgl/src/libs/libpng \
App/Modules/GUI/lvgl/src/libs/libwebp \
App/Modules/GUI/lvgl/src/libs/lodepng \
App/Modules/GUI/lvgl/src/libs/lz4 \
App/Modules/GUI/lvgl/src/libs/nanovg \
App/Modules/GUI/lvgl/src/libs/qrcode \
App/Modules/GUI/lvgl/src/libs/rle \
App/Modules/GUI/lvgl/src/libs/rlottie \
App/Modules/GUI/lvgl/src/libs/svg \
App/Modules/GUI/lvgl/src/libs/tiny_ttf \
App/Modules/GUI/lvgl/src/libs/tjpgd \
App/Modules/GUI/lvgl/src/libs/vg_lite_driver/VGLite \
App/Modules/GUI/lvgl/src/libs/vg_lite_driver/VGLiteKernel \
App/Modules/GUI/lvgl/src/libs/vg_lite_driver/lv_vg_lite_hal \
App/Modules/GUI/lvgl/src \
App/Modules/GUI/lvgl/src/misc/cache/class \
App/Modules/GUI/lvgl/src/misc/cache/instance \
App/Modules/GUI/lvgl/src/misc/cache \
App/Modules/GUI/lvgl/src/misc \
App/Modules/GUI/lvgl/src/osal \
App/Modules/GUI/lvgl/src/others/file_explorer \
App/Modules/GUI/lvgl/src/others/fragment \
App/Modules/GUI/lvgl/src/others/translation \
App/Modules/GUI/lvgl/src/stdlib/builtin \
App/Modules/GUI/lvgl/src/stdlib/clib \
App/Modules/GUI/lvgl/src/stdlib \
App/Modules/GUI/lvgl/src/stdlib/micropython \
App/Modules/GUI/lvgl/src/stdlib/rtthread \
App/Modules/GUI/lvgl/src/stdlib/uefi \
App/Modules/GUI/lvgl/src/themes/default \
App/Modules/GUI/lvgl/src/themes \
App/Modules/GUI/lvgl/src/themes/mono \
App/Modules/GUI/lvgl/src/themes/simple \
App/Modules/GUI/lvgl/src/tick \
App/Modules/GUI/lvgl/src/widgets/3dtexture \
App/Modules/GUI/lvgl/src/widgets/animimage \
App/Modules/GUI/lvgl/src/widgets/arc \
App/Modules/GUI/lvgl/src/widgets/arclabel \
App/Modules/GUI/lvgl/src/widgets/bar \
App/Modules/GUI/lvgl/src/widgets/button \
App/Modules/GUI/lvgl/src/widgets/buttonmatrix \
App/Modules/GUI/lvgl/src/widgets/calendar \
App/Modules/GUI/lvgl/src/widgets/canvas \
App/Modules/GUI/lvgl/src/widgets/chart \
App/Modules/GUI/lvgl/src/widgets/checkbox \
App/Modules/GUI/lvgl/src/widgets/dropdown \
App/Modules/GUI/lvgl/src/widgets/gif \
App/Modules/GUI/lvgl/src/widgets/image \
App/Modules/GUI/lvgl/src/widgets/imagebutton \
App/Modules/GUI/lvgl/src/widgets/ime \
App/Modules/GUI/lvgl/src/widgets/keyboard \
App/Modules/GUI/lvgl/src/widgets/label \
App/Modules/GUI/lvgl/src/widgets/led \
App/Modules/GUI/lvgl/src/widgets/line \
App/Modules/GUI/lvgl/src/widgets/list \
App/Modules/GUI/lvgl/src/widgets/lottie \
App/Modules/GUI/lvgl/src/widgets/menu \
App/Modules/GUI/lvgl/src/widgets/msgbox \
App/Modules/GUI/lvgl/src/widgets/objx_templ \
App/Modules/GUI/lvgl/src/widgets/property \
App/Modules/GUI/lvgl/src/widgets/roller \
App/Modules/GUI/lvgl/src/widgets/scale \
App/Modules/GUI/lvgl/src/widgets/slider \
App/Modules/GUI/lvgl/src/widgets/span \
App/Modules/GUI/lvgl/src/widgets/spinbox \
App/Modules/GUI/lvgl/src/widgets/spinner \
App/Modules/GUI/lvgl/src/widgets/switch \
App/Modules/GUI/lvgl/src/widgets/table \
App/Modules/GUI/lvgl/src/widgets/tabview \
App/Modules/GUI/lvgl/src/widgets/textarea \
App/Modules/GUI/lvgl/src/widgets/tileview \
App/Modules/GUI/lvgl/src/widgets/win \
App/Modules/GUI \
App/Modules/modbus/modbus-manager \
App/Modules/modbus/modbus-manager/port \
App/Modules/modbus/modbus-master \
App/Modules/modbus/modbus-master/port \
App/Modules/modbus/modbus-master/rtu \
App/Modules/modbus/modbus-slave/functions \
App/Modules/modbus/modbus-slave \
App/Modules/modbus/modbus-slave/port \
App/Modules/modbus/modbus-slave/rtu \
App/Modules/modbus/modbus-sniffer \
Core/Src \
Core/Startup \
Drivers/STM32F4xx_HAL_Driver/Src \

